package com.idi.intellij.plugin.query.sqlref.config;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by EAD-MASTER on 2/1/14.
 */
public class SPViewPanelForm {
	private JTextField spNameTextField;
	private JButton closeButton;
	private JButton goDownButton;
	private JButton goUpButton;
	private JTextArea textArea1;
	private JButton spSearchSubmitBtn;
	private JPanel mainPanel;
	private JPanel topPanel;
	private JLabel spNameLabel;
	private JPanel sideToolBarPanel;
	private JPanel textAreaPanel;
	private JPanel sideAndTextPanel;
	private JScrollPane textAreaScrollPane;

	public SPViewPanelForm() {
//		ContentFactory.SERVICE.getInstance().createContent() ;
	}

	public JPanel getMainPanel() {
		return mainPanel;
	}


	private void createUIComponents() {
		spSearchSubmitBtn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {

			}
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
		topPanel = new JPanel();
		topPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(topPanel, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		spNameLabel = new JLabel();
		spNameLabel.setHorizontalAlignment(2);
		spNameLabel.setHorizontalTextPosition(2);
		spNameLabel.setText("SP Name:");
		topPanel.add(spNameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		spNameTextField = new JTextField();
		spNameTextField.setMinimumSize(new Dimension(150, 20));
		spNameTextField.setPreferredSize(new Dimension(150, 20));
		topPanel.add(spNameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		spSearchSubmitBtn = new JButton();
		spSearchSubmitBtn.setText("submit");
		topPanel.add(spSearchSubmitBtn, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		mainPanel.add(spacer1, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		sideAndTextPanel = new JPanel();
		sideAndTextPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		mainPanel.add(sideAndTextPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		textAreaPanel = new JPanel();
		textAreaPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		sideAndTextPanel.add(textAreaPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(500, 150), null, null, 0, false));
		textAreaScrollPane = new JScrollPane();
		textAreaScrollPane.setVerticalScrollBarPolicy(22);
		textAreaPanel.add(textAreaScrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		textArea1 = new JTextArea();
		textAreaScrollPane.setViewportView(textArea1);
		sideToolBarPanel = new JPanel();
		sideToolBarPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
		sideAndTextPanel.add(sideToolBarPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(20, 100), new Dimension(-1, 200), 0, false));
		sideToolBarPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-3355444)), null));
		closeButton = new JButton();
		closeButton.setIcon(new ImageIcon(getClass().getResource("/actions/closeNew.png")));
		closeButton.setText("");
		sideToolBarPanel.add(closeButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(24, 24), new Dimension(24, 24), 0, false));
		goUpButton = new JButton();
		goUpButton.setHorizontalTextPosition(0);
		goUpButton.setIcon(new ImageIcon(getClass().getResource("/com/sun/java/swing/plaf/motif/icons/ScrollUpArrowActive.gif")));
		goUpButton.setText("");
		sideToolBarPanel.add(goUpButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(24, 24), new Dimension(24, 24), 0, false));
		goDownButton = new JButton();
		goDownButton.setBorderPainted(true);
		goDownButton.setHorizontalTextPosition(0);
		goDownButton.setIcon(new ImageIcon(getClass().getResource("/com/sun/java/swing/plaf/motif/icons/ScrollDownArrowActive.gif")));
		goDownButton.setOpaque(true);
		goDownButton.setText("");
		sideToolBarPanel.add(goDownButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(24, 24), new Dimension(24, 24), 0, false));
		spNameLabel.setLabelFor(spNameTextField);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}
}
